### PR TITLE
147 update navbar to be responsive

### PR DESCRIPTION
**Pull request by Ville-Wilson**
## Description
- Updates the navbar to be responsive.
- Removes topbar/AppBar.
- Implements Logo and Title (dark version) to navbar.

## Type of PR
- [x] Feature

## Did you write tests?
- [x] No

## In which environment did you test?
- [x] Development

## steps for code reviewers
- [ ] Fetch changes.
- [ ] Review the new navbar and removed topbar.
- [ ] Inspect page
- [ ] Lower width of screen (or use screen presets, such as a phone).
- [ ] Make sure the navbar closes when screen width is smaller.
- [ ] Make sure all functionality (links and logout) work in the new navbar.

### CODE REVIEW

**Review by vikjoh1 — CHANGES_REQUESTED** [review]
It seems like you have not yet resolved the merge conflict:

image

**Comment by Ville-Wilson** [comment]
> It seems like you have not yet resolved the merge conflict:
> 
> image

I am not seeing or encountering any merge conflicts. Where do you see them?

**Comment by vikjoh1** [comment]
@Ville-Wilson 

image

image

**Comment by Ville-Wilson** [comment]
That is strange..
The merge conflict you encounter is at the very end of the navbar.tsx file, the file with the most changes in this pr.
The list item, seen in your screenshot, with the button with handleDrawerOpen and close should not be present.
I personally do not get these merge conflicts on my computer. I've tried to pull all new changes and restarted everything etc, but no change.

I was hoping maybe @WinterBoii @eejebring and @Issa-morad could also look into this to see if you also get merge conflicts?

**Review by WinterBoii — APPROVED** [review]
Awesome, i am not getting the merge conflicts
LGTM 👍

**Review by vikjoh1 — APPROVED** [review]
I see now that I had a problem with my local branch, but it's resolved now and I can finally see the changes. Looks good!

**Pull request merged**
