### PR TITLE
update node version

### PR DESCRIPTION
**Pull request by Issa-morad**
## Description
Briefly descripe the PR.

## Screenshots
Add if necessary.
Copy paste should work.

## Type of PR
- [ ] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Test
- [x] Code refactor

## Did you write tests?
- [ ] Yes
- [x] No
- [ ] No, I need help

## If you wrote tests, did they pass?
- [ ] Yes
- [x] No
- [ ] No, I need help

## In which environment did you test?
- [x] Development
- [ ] Production (backend API)
- [ ] Didn't test

### example steps (change for your PR):
- [ ] Click on the Active Chargers button
- [ ] Try to edit a charger
- [ ] Refresh the page
- [x] Make sure that it works

### CODE REVIEW

**Comment by Issa-morad** [comment]
node update

**Review by vikjoh1 — CHANGES_REQUESTED** [review]
image

I think this has to do with you using npm. You're trying to install npm using npm? Not sure why. You should probably remove line 6, 7 and 8 from the Dockerfile.

**Comment by vikjoh1** [comment]
Now that I looked into it, you're probably specifying the newest node version instead of the newest node image version. Check here: https://hub.docker.com/_/node/

**Comment by eejebring** [comment]
Since the big update branch have been approved, PR is not necessary.

**Pull request closed without merging**
