### PR TITLE
134 big update

### PR DESCRIPTION
**Pull request by eejebring**
## Description
Updated most packages except for react-router-dom.
Fixed a lot of type errors, ESlint seems to be more aggressive now.

## Screenshots
Add if necessary.
Copy paste should work.

## Type of PR
- [ ] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Test
- [x] Code refactor

## Did you write tests?
- [ ] Yes
- [x] No
- [ ] No, I need help

## In which environment did you test?
- [ ] Development
- [x] Production (backend API)
- [ ] Didn't test

### example steps (change for your PR):
- [ ] Get the bransh and run `yarn install` from the react-app folder
- [ ] Start docker-compose
- [ ] Login and try out some random things that have worked before
- [ ] Make sure that it works

### CODE REVIEW

**Comment by WinterBoii** [comment]
i am not able to run it, getting these kind of errors: 
image

**Review by WinterBoii — APPROVED** [review]
i forgot to clean docker previously.

LGTM

**Review by Ville-Wilson — APPROVED** [review]
image
Everything compiles and works properly for me.
LGTM! 👍

**Review by vikjoh1 — APPROVED** [review]
Compiles and works. But since you didn't update react dom, react will still behave as version 17. Maybe something for next years squad to fix 😄

**Pull request merged**
