### PR TITLE
130 implement managechargers func in mock file

### PR DESCRIPTION
**Pull request by WinterBoii**
## Description
Implemented CRUD operations for the mock data on manage chargers

## Screenshots
Add if necessary.
Copy paste should work.

## Type of PR
- [x] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Test
- [ ] Code refactor

## Did you write tests?
- [x] Yes
- [ ] No
- [ ] No, I need help

## If you wrote tests, did they pass?
- [x] Yes
- [ ] No
- [ ] No, I need help

## In which environment did you test?
- [x] Development
- [ ] Production (backend API)
- [ ] Didn't test

### example steps (change for your PR):
- [ ] Click on the Active Chargers button
- [ ] Try to edit a charger
- [ ] Refresh the page
- [ ] Make sure that it works

### CODE REVIEW

**Review by vikjoh1 — CHANGES_REQUESTED** [review]
The location has to be a tuple with numbers ( [number, number] ), not strings, since it should contain latitude and longitude. 

Here is the expected charger object, taken from the backend:

```
{
  "chargerID": 100011,
  "location": [
    57.777714,
    14.16301
  ],
  "serialNumber": "testnumber15",
  "chargePointID": 24,
  "status": "Available"
}
```

**Comment by vikjoh1** [comment]
The tests should now work as intended. I also moved some logic in ManageCharger to the utilities folder.

**Comment by WinterBoii** [comment]
image

**Review by vikjoh1 — APPROVED** [review]
I approve :)

**Review by eejebring — APPROVED** [review]
Looks good, we should probably merge this one before the Big-update branch since I see a upcoming merge conflict. good work!

**Pull request merged**
