### PR TITLE
124 create alert when logout

### PR DESCRIPTION
**Pull request by Issa-morad**
## Description
Briefly descripe the PR.

## Screenshots
Add if necessary.
Copy paste should work.

## Type of PR
- [x] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Test
- [ ] Code refactor

## Did you write tests?
- [ ] Yes
- [x] No
- [ ] No, I need help

## If you wrote tests, did they pass?
- [ ] Yes
- [x] No
- [ ] No, I need help

## In which environment did you test?
- [x] Development
- [ ] Production (backend API)
- [ ] Didn't test

### example steps (change for your PR):
- [ ] Click on the Active Chargers button
- [ ] Try to edit a charger
- [x] Refresh the page
- [ ] Make sure that it works

### CODE REVIEW

**Comment by Issa-morad** [comment]
create alert when logout

**Review by vikjoh1 — CHANGES_REQUESTED** [review]
It works. But I would suggest using material ui components for this (Dialog component) for better consistency and design.

**Review by vikjoh1 — CHANGES_REQUESTED** [review]
It works. But I would suggest using material ui components for this (Dialog component) for better consistency and design.
Also DO NOT put sensitive information in example.env and push it. That file is an example file only. Put your sensitive information in .env instead.

**Comment by Ville-Wilson** [comment]
Should use material UI (dialog component) instead for the logout confirmation.
Also, should not put sensitive information in the .env example file. Use the .env file instead.

**Pull request closed without merging**
